build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.3.1"
    - "transformers==4.44.2"
    - "accelerate==0.34.2"
    - "autoawq==0.2.6"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.1"
